import type {
  ExampleSectionVariants,
  ExampleTheme,
  ExampleThemeFamily,
} from "@/lib/examples/types";

export const exampleThemes: Record<ExampleThemeFamily, ExampleTheme> = {
  "warm-editorial": {
    family: "warm-editorial",
    label: "Warm / Editorial",
    typography: {
      display: '"Newsreader", "Iowan Old Style", "Palatino Linotype", serif',
      body: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
      label: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
    },
    colors: {
      background: "#fcf9f4",
      surface: "#f6f3ee",
      surfaceAlt: "#f0ede8",
      surfaceStrong: "#e5e2dd",
      text: "#173124",
      muted: "#665d56",
      border: "#d9d4cd",
      primary: "#173124",
      primaryContrast: "#ffffff",
      accent: "#6b301a",
      accentContrast: "#ffffff",
      accentSoft: "#ebddd5",
      heroOverlayFrom: "rgba(23, 49, 36, 0.88)",
      heroOverlayTo: "rgba(23, 49, 36, 0.15)",
    },
    radius: {
      panel: "1.5rem",
      input: "1rem",
      pill: "999px",
    },
    shadow: {
      soft: "0 24px 70px rgba(23, 49, 36, 0.10)",
      strong: "0 32px 90px rgba(23, 49, 36, 0.18)",
    },
  },
  "bold-trust": {
    family: "bold-trust",
    label: "Bold / Trust-First",
    typography: {
      display: '"Epilogue", "Manrope", "Arial Narrow", sans-serif',
      body: '"Inter", "Helvetica Neue", sans-serif',
      label: '"Inter", "Helvetica Neue", sans-serif',
    },
    colors: {
      background: "#f9f9fc",
      surface: "#f3f3f6",
      surfaceAlt: "#eeeef0",
      surfaceStrong: "#e2e2e5",
      text: "#1a1c1e",
      muted: "#43474f",
      border: "#c4c6d1",
      primary: "#00193c",
      primaryContrast: "#ffffff",
      accent: "#fe6b00",
      accentContrast: "#ffffff",
      accentSoft: "#ffdbcc",
      heroOverlayFrom: "rgba(0, 25, 60, 0.96)",
      heroOverlayTo: "rgba(0, 25, 60, 0.55)",
    },
    radius: {
      panel: "1rem",
      input: "0.875rem",
      pill: "999px",
    },
    shadow: {
      soft: "0 20px 50px rgba(0, 27, 63, 0.10)",
      strong: "0 28px 80px rgba(0, 27, 63, 0.20)",
    },
  },
  "premium-professional": {
    family: "premium-professional",
    label: "Premium / Professional",
    typography: {
      display: '"Noto Serif", "Iowan Old Style", "Palatino Linotype", serif',
      body: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
      label: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
    },
    colors: {
      background: "#fcf9f6",
      surface: "#f6f3f0",
      surfaceAlt: "#f0edea",
      surfaceStrong: "#e5e2df",
      text: "#1c1c1a",
      muted: "#516072",
      border: "#d7d2cd",
      primary: "#111c2d",
      primaryContrast: "#ffffff",
      accent: "#cf6721",
      accentContrast: "#ffffff",
      accentSoft: "#d2e1f7",
      heroOverlayFrom: "rgba(252, 249, 246, 0.96)",
      heroOverlayTo: "rgba(252, 249, 246, 0.18)",
    },
    radius: {
      panel: "1.25rem",
      input: "0.75rem",
      pill: "999px",
    },
    shadow: {
      soft: "0 22px 60px rgba(17, 28, 45, 0.08)",
      strong: "0 28px 90px rgba(17, 28, 45, 0.14)",
    },
  },
  "energetic-performance": {
    family: "energetic-performance",
    label: "Energetic / Performance",
    typography: {
      display: '"Space Grotesk", "Manrope", "Helvetica Neue", sans-serif',
      body: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
      label: '"Manrope", "Inter", "Helvetica Neue", sans-serif',
    },
    colors: {
      background: "#f9f6f5",
      surface: "#f3f0ef",
      surfaceAlt: "#eae7e7",
      surfaceStrong: "#dfdcdc",
      text: "#2f2e2e",
      muted: "#5c5b5b",
      border: "#c8c4c4",
      primary: "#0e0e0e",
      primaryContrast: "#ffffff",
      accent: "#ab2d00",
      accentContrast: "#ffefeb",
      accentSoft: "#ff7851",
      heroOverlayFrom: "rgba(14, 14, 14, 0.94)",
      heroOverlayTo: "rgba(14, 14, 14, 0.30)",
    },
    radius: {
      panel: "1.125rem",
      input: "0.875rem",
      pill: "999px",
    },
    shadow: {
      soft: "0 20px 60px rgba(15, 15, 15, 0.12)",
      strong: "0 28px 90px rgba(15, 15, 15, 0.24)",
    },
  },
};

export const defaultSectionVariants: Record<ExampleThemeFamily, ExampleSectionVariants> = {
  "warm-editorial": {
    heroVariant: "editorial-image",
    servicesVariant: "editorial-feature",
    whyChooseUsVariant: "editorial-feature",
    testimonialsVariant: "editorial-quote",
    processVariant: "steps-grid",
    serviceAreaVariant: "chip-list",
    ctaVariant: "editorial-soft",
    contactVariant: "editorial-card",
  },
  "bold-trust": {
    heroVariant: "trust-split",
    servicesVariant: "compact-grid",
    whyChooseUsVariant: "trust-list",
    testimonialsVariant: "review-grid",
    processVariant: "numbered-band",
    serviceAreaVariant: "coverage-list",
    ctaVariant: "bold-band",
    contactVariant: "trust-card",
  },
  "premium-professional": {
    heroVariant: "premium-image",
    servicesVariant: "structured-columns",
    whyChooseUsVariant: "premium-proof",
    testimonialsVariant: "premium-quotes",
    processVariant: "premium-steps",
    serviceAreaVariant: "office-grid",
    ctaVariant: "premium-minimal",
    contactVariant: "premium-form",
  },
  "energetic-performance": {
    heroVariant: "energetic-impact",
    servicesVariant: "image-cards",
    whyChooseUsVariant: "contrast-proof",
    testimonialsVariant: "results-grid",
    processVariant: "momentum-steps",
    serviceAreaVariant: "map-split",
    ctaVariant: "energetic-split",
    contactVariant: "energetic-split",
  },
};
